[buildPlans.IosevkaIllBent]
family = "Iosevka illBent"
spacing = "term"
serifs = "slab"
noCvSs = true
exportGlyphNames = true

  [buildPlans.IosevkaIllBent.variants]
  inherits = "ss14"

  [buildPlans.IosevkaIllBent.ligations]
  inherits = "fsharp"

[buildPlans.IosevkaIllBent.slopes.Upright]
angle = 0
shape = "upright"
menu = "upright"
css = "normal"

[buildPlans.IosevkaIllBent.slopes.Oblique]
angle = 9.4
shape = "oblique"
menu = "oblique"
css = "oblique"
