xrandr --output HDMI-A-0 --rotate right
xset r rate 300 50 &
xmodmap ~/.Xmodmap
xrdb -merge ~/.Xresources
unclutter &
picom -cfF -o 0.38 -O 200 -I 200 -t 0 -l 0 -r 3 -D2 -m 0.88 &
dunst &	
xsetroot -cursor_name left_ptr_watch # cross hand left_ptr left_ptr_watch
xbindkeys &
# set capslock as mod4
setxkbmap -option caps:hyper
exec awesome
